CREATE DATABASE Exercise1;
CREATE TABLE exercise1.EMP_1 (EMP_NUM CHAR(3) NOT NULL, EMP_Lname VARCHAR(15) NULL, EMP_FNAME VARCHAR(15) NULL,
EMP_INITIAL CHAR(1) NULL, EMP_HIREDATE DATE NULL, JOB_CODE CHAR(3) NULL, PRIMARY KEY (EMP_NUM)); 
SELECT * FROM exercise1.emp_1;
INSERT INTO `exercise1`.`emp_1` (`EMP_NUM`, `EMP_Lname`, `EMP_FNAME`, `EMP_INITIAL`, `EMP_HIREDATE`, `JOB_CODE`) 
VALUES ('111', 'Yumang', 'James Bernard', 'G', '2003-07-25', '502');
